# Generated by Django 4.1.4 on 2022-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlistings_startbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlistings",
            name="imageUrl",
            field=models.URLField(default="None"),
        ),
    ]
