# Generated by Django 4.1.4 on 2022-12-21 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctionlistings_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctioncomments",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listComments",
                to="auctions.auctionlistings",
            ),
        ),
        migrations.AlterField(
            model_name="auctioncomments",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userComments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
