# Generated by Django 4.1.4 on 2022-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auctionlistings_latestbidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlistings",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
