# Generated by Django 4.1.4 on 2022-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlistings",
            name="imageUrl",
            field=models.URLField(default="None", max_length=400),
        ),
    ]
