# Generated by Django 4.1.4 on 2022-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_auctionlistings_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlistings",
            name="categories",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="auctionlistings",
            name="imageUrl",
            field=models.URLField(default="", max_length=400),
        ),
    ]
